package it.uniroma3.catenate.ExpenseManagerApp.widgets;

import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;

import com.vaadin.addon.calendar.ui.Calendar;
import com.vaadin.addon.calendar.ui.CalendarComponentEvents.DateClickEvent;
import com.vaadin.addon.calendar.ui.CalendarComponentEvents.EventClick;
import com.vaadin.addon.calendar.ui.CalendarComponentEvents.DateClickHandler;
import com.vaadin.addon.calendar.ui.CalendarComponentEvents.EventClickHandler;
import com.vaadin.addon.calendar.ui.CalendarComponentEvents.WeekClick;
import com.vaadin.addon.calendar.ui.handler.BasicDateClickHandler;
import com.vaadin.addon.calendar.ui.handler.BasicWeekClickHandler;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

public class CalendarWidget extends CustomComponent {

	
	private VerticalLayout calendarLayout;
	private Calendar calendar;
	private EventProvider provider = new EventProvider();
	private GregorianCalendar gregorianCalendar;	

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CalendarWidget() {
		buildMainLayout();
		setCompositionRoot(calendarLayout);

	}

	private void buildMainLayout() {
		calendarLayout = new VerticalLayout();
        calendarLayout.setCaption("Calendar");
        calendarLayout.addStyleName("dummy");
        calendarLayout.setMargin(true);
        buildCalendar();
	}

	private void buildCalendar() {
		calendar = new Calendar(provider);
        calendar.setLocale(Locale.getDefault());
        calendar.setImmediate(true);
        calendar.setSizeFull();

        calendar.setStartDate(new Date());
        calendar.setEndDate(new Date());

        calendar.setHandler(new EventClickHandler() {
            @Override
            public void eventClick(EventClick event) {
                
            }
        });
        
        calendar.setHandler(new DateClickHandler(){
        	@Override
        	public void dateClick(DateClickEvent event){
        		
        	}
        });
        calendarLayout.addComponent(calendar);
	}
}
