package it.uniroma3.catenate.ExpenseManagerApp.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class EventBuilderWidget extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button addExpButt;
	@AutoGenerated
	private VerticalLayout selectionLayout;
	@AutoGenerated
	private HorizontalLayout locationsBar;
	@AutoGenerated
	private ComboBox locationSelection;
	@AutoGenerated
	private Label locLab;
	@AutoGenerated
	private HorizontalLayout organizationBar;
	@AutoGenerated
	private ComboBox organizationSelection;
	@AutoGenerated
	private Label orgLabel;
	@AutoGenerated
	private VerticalLayout eventFieldLayout;
	@AutoGenerated
	private TextArea notesField;
	@AutoGenerated
	private HorizontalLayout dateNameLayout;
	@AutoGenerated
	private TextField nameField;
	@AutoGenerated
	private PopupDateField dateField;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Label spaceTitle2;
	@AutoGenerated
	private Label titleLabel;
	@AutoGenerated
	private Label spaceTitle1;
	/**
	 * 
	 */
	private static final long serialVersionUID = -1703727138372402261L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EventBuilderWidget() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		titleLabel.setContentMode(ContentMode.HTML);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		
		// eventFieldLayout
		eventFieldLayout = buildEventFieldLayout();
		mainLayout.addComponent(eventFieldLayout);
		
		// selectionLayout
		selectionLayout = buildSelectionLayout();
		mainLayout.addComponent(selectionLayout);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("5.0em");
		horizontalLayout_3.setMargin(false);
		
		// spaceTitle1
		spaceTitle1 = new Label();
		spaceTitle1.setImmediate(false);
		spaceTitle1.setWidth("100.0%");
		spaceTitle1.setHeight("-1px");
		horizontalLayout_3.addComponent(spaceTitle1);
		horizontalLayout_3.setExpandRatio(spaceTitle1, 0.3f);
		
		// titleLabel
		titleLabel = new Label();
		titleLabel.setImmediate(false);
		titleLabel.setWidth("-1px");
		titleLabel.setHeight("-1px");
		titleLabel.setValue("<h3>Main Informations</h3>");
		horizontalLayout_3.addComponent(titleLabel);
		horizontalLayout_3.setExpandRatio(titleLabel, 1.0f);
		horizontalLayout_3.setComponentAlignment(titleLabel, new Alignment(48));
		
		// spaceTitle2
		spaceTitle2 = new Label();
		spaceTitle2.setImmediate(false);
		spaceTitle2.setWidth("100.0%");
		spaceTitle2.setHeight("-1px");
		horizontalLayout_3.addComponent(spaceTitle2);
		horizontalLayout_3.setExpandRatio(spaceTitle2, 0.3f);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildEventFieldLayout() {
		// common part: create layout
		eventFieldLayout = new VerticalLayout();
		eventFieldLayout.setImmediate(false);
		eventFieldLayout.setWidth("-1px");
		eventFieldLayout.setHeight("-1px");
		eventFieldLayout.setMargin(false);
		eventFieldLayout.setSpacing(true);
		
		// dateNameLayout
		dateNameLayout = buildDateNameLayout();
		eventFieldLayout.addComponent(dateNameLayout);
		
		// notesField
		notesField = new TextArea();
		notesField.setCaption("Notes:");
		notesField.setImmediate(false);
		notesField.setWidth("100.0%");
		notesField.setHeight("-1px");
		eventFieldLayout.addComponent(notesField);
		eventFieldLayout.setExpandRatio(notesField, 1.0f);
		
		return eventFieldLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildDateNameLayout() {
		// common part: create layout
		dateNameLayout = new HorizontalLayout();
		dateNameLayout.setImmediate(false);
		dateNameLayout.setWidth("-1px");
		dateNameLayout.setHeight("-1px");
		dateNameLayout.setMargin(false);
		dateNameLayout.setSpacing(true);
		
		// dateField
		dateField = new PopupDateField();
		dateField.setCaption("Date");
		dateField.setImmediate(false);
		dateField.setWidth("-1px");
		dateField.setHeight("100.0%");
		dateNameLayout.addComponent(dateField);
		
		// nameField
		nameField = new TextField();
		nameField.setCaption("Name of the event");
		nameField.setImmediate(false);
		nameField.setWidth("23.0em");
		nameField.setHeight("100.0%");
		dateNameLayout.addComponent(nameField);
		dateNameLayout.setExpandRatio(nameField, 1.0f);
		dateNameLayout.setComponentAlignment(nameField, new Alignment(6));
		
		return dateNameLayout;
	}

	@AutoGenerated
	private VerticalLayout buildSelectionLayout() {
		// common part: create layout
		selectionLayout = new VerticalLayout();
		selectionLayout.setImmediate(false);
		selectionLayout.setWidth("100.0%");
		selectionLayout.setHeight("-1px");
		selectionLayout.setMargin(false);
		selectionLayout.setSpacing(true);
		
		// organizationBar
		organizationBar = buildOrganizationBar();
		selectionLayout.addComponent(organizationBar);
		
		// locationsBar
		locationsBar = buildLocationsBar();
		selectionLayout.addComponent(locationsBar);
		
		return selectionLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildOrganizationBar() {
		// common part: create layout
		organizationBar = new HorizontalLayout();
		organizationBar.setImmediate(false);
		organizationBar.setWidth("100.0%");
		organizationBar.setHeight("100.0%");
		organizationBar.setMargin(false);
		organizationBar.setSpacing(true);
		
		// orgLabel
		orgLabel = new Label();
		orgLabel.setImmediate(false);
		orgLabel.setWidth("100.0%");
		orgLabel.setHeight("100.0%");
		orgLabel.setValue("Select Organization");
		organizationBar.addComponent(orgLabel);
		organizationBar.setExpandRatio(orgLabel, 1.0f);
		
		// organizationSelection
		organizationSelection = new ComboBox();
		organizationSelection.setImmediate(false);
		organizationSelection.setWidth("100.0%");
		organizationSelection.setHeight("-1px");
		organizationBar.addComponent(organizationSelection);
		organizationBar.setExpandRatio(organizationSelection, 1.5f);
		
		return organizationBar;
	}

	@AutoGenerated
	private HorizontalLayout buildLocationsBar() {
		// common part: create layout
		locationsBar = new HorizontalLayout();
		locationsBar.setImmediate(false);
		locationsBar.setWidth("100.0%");
		locationsBar.setHeight("100.0%");
		locationsBar.setMargin(false);
		locationsBar.setSpacing(true);
		
		// locLab
		locLab = new Label();
		locLab.setImmediate(false);
		locLab.setWidth("100.0%");
		locLab.setHeight("100.0%");
		locLab.setValue("Select one or more location");
		locationsBar.addComponent(locLab);
		locationsBar.setExpandRatio(locLab, 1.0f);
		
		// locationSelection
		locationSelection = new ComboBox();
		locationSelection.setImmediate(false);
		locationSelection.setWidth("100.0%");
		locationSelection.setHeight("-1px");
		locationsBar.addComponent(locationSelection);
		locationsBar.setExpandRatio(locationSelection, 1.5f);
		
		return locationsBar;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// addExpButt
		addExpButt = new Button();
		addExpButt.setCaption("Add Expenses");
		addExpButt.setImmediate(true);
		addExpButt.setWidth("-1px");
		addExpButt.setHeight("-1px");
		horizontalLayout_1.addComponent(addExpButt);
		
		return horizontalLayout_1;
	}

}
