package it.uniroma3.catenate.ExpenseManagerApp.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.VerticalLayout;

public class EventBuilderWidget extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout buttonLayout;
	@AutoGenerated
	private Button deleteButton;
	@AutoGenerated
	private Button discardButton;
	@AutoGenerated
	private Button saveButton;
	@AutoGenerated
	private HorizontalLayout editPropertyLayout;
	@AutoGenerated
	private VerticalLayout selectionLayout;
	@AutoGenerated
	private TwinColSelect locationsSelection;
	@AutoGenerated
	private ListSelect organizationSelection;
	@AutoGenerated
	private VerticalLayout eventFieldLayout;
	@AutoGenerated
	private TextArea notesField;
	@AutoGenerated
	private HorizontalLayout dateNameLayout;
	@AutoGenerated
	private TextField nameField;
	@AutoGenerated
	private PopupDateField dateField;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EventBuilderWidget() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// editPropertyLayout
		editPropertyLayout = buildEditPropertyLayout();
		mainLayout.addComponent(editPropertyLayout);
		mainLayout.setExpandRatio(editPropertyLayout, 1.0f);
		
		// buttonLayout
		buttonLayout = buildButtonLayout();
		mainLayout.addComponent(buttonLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildEditPropertyLayout() {
		// common part: create layout
		editPropertyLayout = new HorizontalLayout();
		editPropertyLayout.setImmediate(false);
		editPropertyLayout.setWidth("100.0%");
		editPropertyLayout.setHeight("-1px");
		editPropertyLayout.setMargin(false);
		
		// eventFieldLayout
		eventFieldLayout = buildEventFieldLayout();
		editPropertyLayout.addComponent(eventFieldLayout);
		
		// selectionLayout
		selectionLayout = buildSelectionLayout();
		editPropertyLayout.addComponent(selectionLayout);
		editPropertyLayout.setExpandRatio(selectionLayout, 1.0f);
		
		return editPropertyLayout;
	}

	@AutoGenerated
	private VerticalLayout buildEventFieldLayout() {
		// common part: create layout
		eventFieldLayout = new VerticalLayout();
		eventFieldLayout.setCaption("Main Informations:");
		eventFieldLayout.setImmediate(false);
		eventFieldLayout.setWidth("-1px");
		eventFieldLayout.setHeight("-1px");
		eventFieldLayout.setMargin(true);
		eventFieldLayout.setSpacing(true);
		
		// dateNameLayout
		dateNameLayout = buildDateNameLayout();
		eventFieldLayout.addComponent(dateNameLayout);
		
		// notesField
		notesField = new TextArea();
		notesField.setCaption("Notes:");
		notesField.setImmediate(false);
		notesField.setWidth("100.0%");
		notesField.setHeight("20.0em");
		eventFieldLayout.addComponent(notesField);
		eventFieldLayout.setExpandRatio(notesField, 1.0f);
		
		return eventFieldLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildDateNameLayout() {
		// common part: create layout
		dateNameLayout = new HorizontalLayout();
		dateNameLayout.setImmediate(false);
		dateNameLayout.setWidth("-1px");
		dateNameLayout.setHeight("-1px");
		dateNameLayout.setMargin(false);
		dateNameLayout.setSpacing(true);
		
		// dateField
		dateField = new PopupDateField();
		dateField.setCaption("Date");
		dateField.setImmediate(false);
		dateField.setWidth("-1px");
		dateField.setHeight("-1px");
		dateNameLayout.addComponent(dateField);
		
		// nameField
		nameField = new TextField();
		nameField.setCaption("Name of the event");
		nameField.setImmediate(false);
		nameField.setWidth("23.0em");
		nameField.setHeight("1.5em");
		dateNameLayout.addComponent(nameField);
		dateNameLayout.setExpandRatio(nameField, 1.0f);
		dateNameLayout.setComponentAlignment(nameField, new Alignment(6));
		
		return dateNameLayout;
	}

	@AutoGenerated
	private VerticalLayout buildSelectionLayout() {
		// common part: create layout
		selectionLayout = new VerticalLayout();
		selectionLayout.setImmediate(false);
		selectionLayout.setWidth("100.0%");
		selectionLayout.setHeight("100.0%");
		selectionLayout.setMargin(true);
		selectionLayout.setSpacing(true);
		
		// organizationSelection
		organizationSelection = new ListSelect();
		organizationSelection.setImmediate(false);
		organizationSelection.setWidth("100.0%");
		organizationSelection.setHeight("-1px");
		selectionLayout.addComponent(organizationSelection);
		
		// locationsSelection
		locationsSelection = new TwinColSelect();
		locationsSelection.setImmediate(false);
		locationsSelection.setWidth("100.0%");
		locationsSelection.setHeight("-1px");
		selectionLayout.addComponent(locationsSelection);
		selectionLayout.setExpandRatio(locationsSelection, 1.0f);
		
		return selectionLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildButtonLayout() {
		// common part: create layout
		buttonLayout = new HorizontalLayout();
		buttonLayout.setImmediate(false);
		buttonLayout.setWidth("50.0%");
		buttonLayout.setHeight("-1px");
		buttonLayout.setMargin(true);
		buttonLayout.setSpacing(true);
		
		// saveButton
		saveButton = new Button();
		saveButton.setCaption("Save Event");
		saveButton.setImmediate(false);
		saveButton.setWidth("100.0%");
		saveButton.setHeight("-1px");
		buttonLayout.addComponent(saveButton);
		
		// discardButton
		discardButton = new Button();
		discardButton.setCaption("Discard Changes");
		discardButton.setImmediate(false);
		discardButton.setWidth("100.0%");
		discardButton.setHeight("-1px");
		buttonLayout.addComponent(discardButton);
		buttonLayout.setComponentAlignment(discardButton, new Alignment(10));
		
		// deleteButton
		deleteButton = new Button();
		deleteButton.setCaption("Delete Event");
		deleteButton.setImmediate(false);
		deleteButton.setWidth("100.0%");
		deleteButton.setHeight("-1px");
		buttonLayout.addComponent(deleteButton);
		buttonLayout.setComponentAlignment(deleteButton, new Alignment(10));
		
		return buttonLayout;
	}

}
