package it.uniroma3.catenate.ExpenseManagerApp.views;

import it.uniroma3.catenate.ExpenseManagerApp.widgets.CalendarWidget;
import it.uniroma3.catenate.ExpenseManagerApp.widgets.EventBuilderWidget;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;

public class DashBoardView extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout eventBuildLayout;
	@AutoGenerated
	private EventBuilderWidget eventBuilderWidget;
	@AutoGenerated
	private CalendarWidget calendarWidget;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DashBoardView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// eventBuildLayout
		eventBuildLayout = buildEventBuildLayout();
		mainLayout.addComponent(eventBuildLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildEventBuildLayout() {
		// common part: create layout
		eventBuildLayout = new HorizontalLayout();
		eventBuildLayout.setImmediate(false);
		eventBuildLayout.setWidth("100.0%");
		eventBuildLayout.setHeight("100.0%");
		eventBuildLayout.setMargin(false);
		
		// calendarWidget
		calendarWidget = new CalendarWidget();
		calendarWidget.setImmediate(false);
		calendarWidget.setWidth("100.0%");
		calendarWidget.setHeight("100.0%");
		eventBuildLayout.addComponent(calendarWidget);
		
		// eventBuilderWidget
		eventBuilderWidget = new EventBuilderWidget();
		eventBuilderWidget.setImmediate(false);
		eventBuilderWidget.setWidth("100.0%");
		eventBuilderWidget.setHeight("100.0%");
		eventBuildLayout.addComponent(eventBuilderWidget);
		
		return eventBuildLayout;
	}

}
