package it.uniroma3.catenate.ExpenseManagerApp.model;

// Generated Oct 6, 2014 12:24:29 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category implements java.io.Serializable {

	private int id;
	private Set<SubCategory> subCategorys = new HashSet<SubCategory>(0);
	private String name;

	public Category() {
	}

	public Category(int id) {
		this.id = id;
	}

	public Category(int id, Set<SubCategory> subCategorys, String name) {
		this.id = id;
		this.subCategorys = subCategorys;
		this.name = name;
	}

	@Id
	@Column(name = "id", nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToMany(fetch =FetchType.EAGER, mappedBy="category")
	public Set<SubCategory> getSubCategorys() {
		return this.subCategorys;
	}

	public void setSubCategorys(Set<SubCategory> subCategorys) {
		this.subCategorys = subCategorys;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
