package it.uniroma3.catenate.ExpenseManagerApp.model;

// Generated Oct 6, 2014 12:24:29 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Money generated by hbm2java
 */
@Embeddable
public class Money implements java.io.Serializable {

	@Column(name="amount")private Integer amount;

	public Money() {
	}

	public Money(Integer amount) {
		super();
		this.amount = amount;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
