package it.uniroma3.catenate.ExpenseManagerApp.model;

// Generated Oct 6, 2014 12:24:29 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Embedded;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name = "subcategory")
public class SubCategory implements java.io.Serializable {

	private int id;
	private Category category;
	private Money basePrice;
	private String name;
	private int maxQuantity;

	public SubCategory() {
	}

	public SubCategory(Category category, Money basePrice, String name,
			int maxQuantity) {
		this.category = category;
		this.basePrice = basePrice;
		this.name = name;
		this.maxQuantity = maxQuantity;
	}

	@Id
	@Column(name = "id", nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CATEGORY_ID")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Embedded
	@AttributeOverrides(@AttributeOverride(name = "amount", column = @Column(name = "BASE_PRICE")))
	public Money getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(Money basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "maxquantity")
	public int getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(int maxQuantity) {
		this.maxQuantity = maxQuantity;
	}

}
