package it.uniroma3.catenate.ExpenseManagerApp.model;

// Generated Oct 6, 2014 12:24:29 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Embedded;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name = "subcategory")
public class SubCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1240468979738128425L;
	private int id;
	private Category category;
	private Money basePrice;
	private String name;
	private int maxQuantity;
	private Integer version;

	public SubCategory() {
	}

	public SubCategory(Category category, Money basePrice, String name,
			int maxQuantity) {
		this.category = category;
		this.basePrice = basePrice;
		this.name = name;
		this.maxQuantity = maxQuantity;
	}

	@Id
	@Column(name = "id", nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CATEGORY_ID")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Embedded
	@AttributeOverrides(@AttributeOverride(name = "amount", column = @Column(name = "BASE_PRICE")))
	public Money getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(Money basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "maxquantity")
	public int getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(int maxQuantity) {
		this.maxQuantity = maxQuantity;
	}
	
	@Version
	@Column(name = "version", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((category == null) ? 0 : category.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SubCategory other = (SubCategory) obj;
		if (category == null) {
			if (other.category != null)
				return false;
		} else if (!category.equals(other.category))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

}
